"""Build `site/site_data.js`: everything the web app renders, generated from the pipeline.

The app reads only this file. No count is ever typed into the UI, which is the failure mode of the previous
engine's dashboard (hard-coded ranking numbers that went stale when the dataset changed).
"""
from __future__ import annotations

import json

from . import config
from . import narrative as NR
from .decomposition import ATTRIBUTION_RULES, NODES, PRODUCTION_NOTE

RECORD_COLUMNS = ["record_id", "source", "relevance", "object_text", "object_class", "object_class_basis",
                  "memory_text", "behavior_text", "closer_text", "retrieval_state", "outcome", "journey_stages",
                  "severity_signals", "express_barrier", "scenario", "raw_text", "offtopic_topic"]


def _records(df):
    cols = [c for c in RECORD_COLUMNS if c in df.columns]
    out = df[cols].fillna("").astype(str)
    return dict(columns=cols, rows=out.values.tolist())


def _index_as_positions(index, order):
    """evidence key -> positions in the records array (smaller than repeating record IDs)."""
    pos = {rid: i for i, rid in enumerate(order)}
    return {k: [pos[r] for r in ids if r in pos] for k, ids in index.items()}


def _narrative(m, ctx) -> dict:
    """Prose the app shows, from the same module the report uses."""
    return dict(
        needs=NR.NEEDS,
        segment_defs=NR.SEGMENT_DEFS,
        opportunities={k: {a: b for a, b in v.items() if a != "quote"} for k, v in NR.opportunities(ctx).items()},
        hypotheses=[dict(name=h[0], node=h[1], key=h[2], observation=h[3], interpretation=h[4], hypothesis=h[5],
                         rival=h[6], test=h[7], evidence_for=h[8], evidence_against=h[9], unknown=h[10],
                         qualitative=NR.MODES[h[0][:2]][0], quantitative=NR.MODES[h[0][:2]][1],
                         verdict="untested") for h in NR.hypotheses(ctx)],
        interview_guide=[dict(part=g[0], questions=g[1], note=g[2]) for g in NR.INTERVIEW_GUIDE],
        tasks=[dict(name=t[0], scenario=t[1], provided=t[2], withheld=t[3], observe=t[4],
                    primary=NR.TASK_PRIMARY[t[0].split()[0]], qualitative=NR.TASK_QUALITATIVE[t[0].split()[0]])
               for t in NR.TASKS],
        decomposition_nodes=NODES,
        attribution_rules=[dict(node=n, rule=r) for n, r in ATTRIBUTION_RULES],
        production_note=PRODUCTION_NOTE,
    )


def export_site(precomputed=None) -> int:
    from .analyze import compute
    from .report import _in

    m, df, r = precomputed or compute()
    E = len(r)
    S = m["segments"]
    O1 = next(v for k, v in m["opps"].items() if k.startswith("O1"))
    S1 = next(v for k, v in S.items() if k.startswith("SEG-1"))
    exit_o1 = sum(O1["profile"]["outcomes"][k] for k in ["failed", "abandoned", "external_workaround"])
    recog = int((_in(r["memory_code"], "M05") | _in(r["closer_code"], "C01")).sum())

    def ev(col, prefix, k=2):
        cmap = {"memory_code": "memory_text", "behavior_code": "behavior_text", "closer_code": "closer_text"}
        sub = r[_in(r[col], prefix)].sort_values("record_id").head(k)
        return "; ".join(f'{a} "{b}"' for a, b in zip(sub.record_id, sub[cmap[col]]))

    ctx = dict(s1=m["stage1"], ev=ev, S1=S1, J=m["journey"], ind=m["independence"],
               pct=lambda a, b: f"{100 * a / b:.1f}%", O1=O1, E=E, recog=recog,
               exit_o1=exit_o1, exit_all=S1["n"])

    index = m["evidence_index"]
    order = df["record_id"].tolist()
    payload = {k: v for k, v in m.items() if k != "evidence_index"}
    payload["records"] = _records(df)
    payload["evidence_index"] = _index_as_positions(index, order)
    payload["narrative"] = _narrative(m, ctx)
    payload["derived"] = dict(relevant=E, recognition_retained=recog, exit_o1=exit_o1,
                              exit_all=S1["n"], opp_count=len(m["opps"]))

    config.OUTPUT.mkdir(parents=True, exist_ok=True)
    site_dir = config.ROOT / "site"
    site_dir.mkdir(exist_ok=True)
    body = json.dumps(payload, default=int, ensure_ascii=False, separators=(",", ":"))
    (site_dir / "site_data.js").write_text(
        "// GENERATED by engine/export_site.py. Do not edit: run `python -m engine.run`.\n"
        f"window.SITE_DATA = {body};\n", encoding="utf-8")
    return len(order)


if __name__ == "__main__":
    config.configure()
    print(f"site/site_data.js: {export_site()} records")
