"""SYNTHETIC / SIMULATED content pools used to generate the development dataset.

Nothing here is a real user statement. Episodes are hand-written, coherent
"memory bundles" that the generator recombines with platform-specific phrasing.

Clue grammar (so templates stay grammatical):
  place       prepositional phrase        "near the beach in north Goa"
  trip        noun phrase                 "our Goa trip"
  event       noun phrase                 "my cousin's wedding"
  occasion    noun phrase                 "grandpa's 80th birthday"
  person      noun phrase                 "my college friends"
  object      noun phrase                 "a strip of antibiotics"
  visual      noun phrase                 "blue wooden chairs"
  time        adverbial phrase            "sometime in December, maybe 2021"
  text        noun phrase                 "something about a refund"
  context     clause                      "we were waiting for the ferry"
  activity    gerund phrase               "eating fish thali"
  relationship noun phrase                "the one my mom forwarded me"
  emotion     sentence fragment           "it was such a happy day"
"""

SCENARIOS: dict[str, dict] = {
    "travel_memory": {
        "weight": 1.4, "object": "photo",
        "outcomes": {"found": 0.30, "not_found": 0.25, "abandoned": 0.15, "partially_found": 0.15, "uncertain": 0.15},
        "failures": {"D_result_evaluation": 0.30, "A_memory_expression": 0.2, "B_system_understanding": 0.25, "E_refinement": 0.15, "C_retrieval": 0.10},
        "episodes": [
            {"item": "a photo of the tiny café we found in Goa", "place": "somewhere near the beach in north Goa", "trip": "our Goa trip",
             "time": "sometime in December, maybe 2021 or 2022", "visual": "blue wooden chairs and a hand-painted menu board", "person": "my college friends",
             "kw": "cafe", "nl": "small cafe with blue chairs near the beach", "meta": "goa 2022", "syn": "restaurant", "need": "my friend is going to Goa and asked for the name",
             "forget": ["exact_location_unknown", "exact_date_unknown"]},
            {"item": "the picture of the houseboat we stayed on", "place": "somewhere in the Kerala backwaters", "trip": "our family trip to Kerala",
             "time": "a few years ago, before covid I think", "visual": "a wooden roof and my dad standing at the front", "person": "my parents",
             "kw": "houseboat", "nl": "dad standing on a boat with a wooden roof", "meta": "kerala 2019", "syn": "boat", "need": "I wanted to print it for my parents' anniversary",
             "forget": ["exact_date_unknown", "exact_location_unknown"]},
            {"item": "a sunset photo from the hotel balcony", "place": "at the hotel near the lake", "trip": "that Switzerland trip",
             "time": "in summer, I'm not sure which year", "visual": "an orange sky and a red railing in the corner", "person": "my wife",
             "kw": "sunset", "nl": "sunset from hotel balcony with red railing", "meta": "switzerland july", "syn": "evening sky", "need": "I want to use it as a wallpaper again",
             "forget": ["exact_date_unknown", "exact_location_unknown"]},
            {"item": "the photo of the street where we got lost", "place": "in some old town in Portugal", "trip": "our honeymoon",
             "time": "on the third or fourth day of the trip", "visual": "yellow tiles on the walls and a tram line", "person": "my husband",
             "kw": "street", "nl": "narrow street with yellow tiles and tram", "meta": "lisbon", "syn": "alley", "need": "we want to frame it",
             "forget": ["exact_location_unknown", "event_name_unknown"]},
            {"item": "a picture of the waterfall we hiked to", "place": "a couple of hours from the homestay", "trip": "the Meghalaya road trip",
             "time": "during monsoon, around 2020", "visual": "mist everywhere and everyone in raincoats", "person": "my cousins",
             "kw": "waterfall", "nl": "waterfall with people in raincoats and mist", "meta": "meghalaya 2020", "syn": "falls", "need": "my cousin asked for it for a reunion slideshow",
             "forget": ["exact_location_unknown", "exact_date_unknown"]},
            {"item": "the photo of the view from the train window", "place": "on the train somewhere between two cities", "trip": "the Europe backpacking trip",
             "time": "in 2018 or 2019, can't pin it down", "visual": "green hills and a reflection of my face in the glass", "person": "nobody, it was just me",
             "kw": "train", "nl": "view from train window with green hills", "meta": "train 2018", "syn": "railway", "need": "I was telling someone about the trip and wanted to show them",
             "forget": ["exact_date_unknown", "exact_location_unknown"]},
        ],
    },
    "food_restaurant_memory": {
        "weight": 1.0, "object": "photo",
        "outcomes": {"found": 0.25, "not_found": 0.30, "abandoned": 0.20, "partially_found": 0.15, "uncertain": 0.10},
        "failures": {"B_system_understanding": 0.35, "D_result_evaluation": 0.25, "A_memory_expression": 0.2, "E_refinement": 0.2},
        "episodes": [
            {"item": "the photo of the dessert we ordered at that restaurant", "place": "at some rooftop place in Bangalore", "event": "my sister's birthday dinner",
             "time": "last year, maybe around October", "visual": "a chocolate dome with gold stuff on top", "person": "my sister",
             "kw": "dessert", "nl": "chocolate dessert with gold on top", "meta": "bangalore october", "syn": "cake", "need": "I want to go back but forgot the restaurant name",
             "forget": ["exact_location_unknown", "event_name_unknown"]},
            {"item": "a picture of the ramen bowl from the tiny shop", "place": "near the station in Tokyo", "trip": "the Japan trip",
             "time": "spring 2023 I think", "visual": "a black bowl with a soft egg cut in half", "person": "my brother",
             "kw": "ramen", "nl": "ramen bowl with egg at a small shop near station", "meta": "tokyo april 2023", "syn": "noodles", "need": "a friend wants the shop name",
             "forget": ["exact_location_unknown", "exact_object_name_unknown"]},
            {"item": "the photo of the menu at the street food stall", "place": "somewhere in Old Delhi", "activity": "eating chaat after the market",
             "time": "a winter evening, not sure which year", "visual": "a handwritten board in Hindi", "text": "the prices and the name of the stall",
             "kw": "menu", "nl": "handwritten street food menu board", "meta": "delhi winter", "syn": "food board", "need": "I want to recommend it to someone visiting",
             "forget": ["exact_text_unknown", "exact_location_unknown", "exact_date_unknown"]},
            {"item": "the picture of the wine label from our anniversary dinner", "place": "at the Italian place downtown", "occasion": "our 5th anniversary",
             "time": "a couple of years back", "visual": "a label with a drawing of a bird", "person": "my partner",
             "kw": "wine", "nl": "wine bottle with bird drawing on label", "meta": "anniversary 2023", "syn": "bottle", "need": "I want to buy the same wine again",
             "forget": ["exact_object_name_unknown", "exact_text_unknown"]},
            {"item": "a photo of the biryani my grandmother made", "place": "at my grandmother's house", "occasion": "Eid",
             "time": "a few Eids ago", "visual": "a huge copper pot and her hands in the shot", "person": "my grandmother",
             "kw": "biryani", "nl": "grandma serving biryani from a copper pot", "meta": "eid 2021", "syn": "rice", "need": "she passed away and I really want that picture",
             "forget": ["exact_date_unknown"], "emotion": "it means a lot to me"},
        ],
    },
    "family_memory": {
        "weight": 1.1, "object": "photo",
        "outcomes": {"found": 0.30, "not_found": 0.25, "abandoned": 0.15, "partially_found": 0.10, "uncertain": 0.20},
        "failures": {"D_result_evaluation": 0.30, "C_retrieval": 0.20, "F_data_index_limitation": 0.20, "E_refinement": 0.15, "A_memory_expression": 0.15},
        "episodes": [
            {"item": "the photo of my son's first steps", "place": "in our old apartment's living room", "person": "my son",
             "time": "when he was around one, so 2019 probably", "visual": "the green rug and him holding the sofa", "relationship": "the one my wife took, not me",
             "kw": "baby walking", "nl": "baby standing holding sofa on green rug", "meta": "2019", "syn": "toddler", "need": "we're making a birthday album",
             "forget": ["exact_date_unknown", "album_unknown"]},
            {"item": "a picture of my dad teaching my daughter to ride a bike", "place": "in the park near my parents' place", "person": "my dad and my daughter",
             "time": "one summer, 3 or 4 years ago", "visual": "a pink bicycle and dad in his old cap", "activity": "learning to ride a bike",
             "kw": "bicycle", "nl": "grandfather teaching girl to ride pink bike", "meta": "summer 2022", "syn": "cycle", "need": "it's for my dad's retirement card",
             "forget": ["exact_date_unknown"]},
            {"item": "the family photo from Diwali where everyone is wearing white", "place": "at my aunt's house", "occasion": "Diwali",
             "time": "one of the Diwalis between 2017 and 2020", "visual": "everyone in white kurtas with diyas in front", "person": "the whole extended family",
             "kw": "diwali", "nl": "family in white clothes with diyas", "meta": "diwali 2018", "syn": "festival", "need": "my aunt asked me to send it",
             "forget": ["exact_date_unknown"]},
            {"item": "the old scanned photo of my grandparents' wedding", "relationship": "a scan my uncle sent me", "person": "my grandparents",
             "time": "I scanned or received it maybe 5 years ago", "visual": "black and white, grandma in a big necklace", "context": "it came through WhatsApp at some point",
             "kw": "old photo", "nl": "black and white wedding photo grandparents", "meta": "scan", "syn": "vintage", "need": "we're printing a family tree",
             "forget": ["exact_date_unknown", "metadata_unknown"]},
            {"item": "the video of my mom singing at the dinner table", "place": "at home", "person": "my mom", "object_type": "video",
             "time": "some Sunday a couple of years ago", "visual": "mom laughing halfway through and the candle on the table", "activity": "singing an old song",
             "kw": "mom singing", "nl": "video of mom singing at dinner", "meta": "sunday dinner", "syn": "song", "need": "I want to play it at her 60th",
             "forget": ["exact_date_unknown"]},
        ],
    },
    "friend_memory": {
        "weight": 0.8, "object": "photo",
        "outcomes": {"found": 0.30, "not_found": 0.25, "abandoned": 0.20, "partially_found": 0.10, "uncertain": 0.15},
        "failures": {"C_retrieval": 0.25, "A_memory_expression": 0.25, "F_data_index_limitation": 0.2, "E_refinement": 0.3},
        "episodes": [
            {"item": "the group photo from the night we all stayed up on the terrace", "place": "on my friend's terrace", "person": "the whole hostel gang",
             "time": "final year of college, so around 2016", "visual": "fairy lights and everyone squinting because of the flash", "context": "it was the night before someone moved abroad",
             "kw": "terrace", "nl": "friends on terrace at night with fairy lights", "meta": "2016 night", "syn": "rooftop", "need": "one of them is getting married and we're making a video",
             "forget": ["exact_date_unknown", "person_name_unknown"]},
            {"item": "a photo with a guy we met on a trek", "place": "at the top of the trek", "person": "a guy from Germany we met on the way",
             "time": "2019 I think", "visual": "a yellow jacket and a flag behind us", "trip": "the Himachal trek",
             "kw": "trek", "nl": "photo with foreigner in yellow jacket on mountain top", "meta": "himachal 2019", "syn": "hike", "need": "I found him on Instagram and wanted to send it",
             "forget": ["person_name_unknown", "exact_location_unknown"]},
            {"item": "the selfie from the concert", "event": "the Coldplay concert", "person": "my best friend",
             "time": "not sure if it was the first or second day", "visual": "confetti in the air behind us", "context": "my phone was almost dead",
             "kw": "concert", "nl": "selfie at concert with confetti", "meta": "coldplay", "syn": "show", "need": "it's her birthday and I want to post it",
             "forget": ["exact_date_unknown"]},
            {"item": "the photo of us at the football match", "place": "in the stadium", "person": "my school friends",
             "time": "some time after school ended", "visual": "all of us with painted faces", "event": "the derby match",
             "kw": "stadium", "nl": "friends with painted faces at football match", "meta": "football", "syn": "match", "need": "reunion group chat asked for it",
             "forget": ["exact_date_unknown", "event_name_unknown"]},
        ],
    },
    "event_memory": {
        "weight": 0.9, "object": "photo",
        "outcomes": {"found": 0.30, "not_found": 0.20, "abandoned": 0.15, "partially_found": 0.20, "uncertain": 0.15},
        "failures": {"D_result_evaluation": 0.45, "B_system_understanding": 0.2, "E_refinement": 0.2, "C_retrieval": 0.15},
        "episodes": [
            {"item": "the photo of the stage when they announced the results", "event": "my company's annual awards night", "person": "my team",
             "time": "around the end of the year, 2022 or 2023", "visual": "purple lights and a big screen with my name", "context": "I was holding a trophy",
             "kw": "award", "nl": "me on stage with trophy under purple lights", "meta": "awards december", "syn": "trophy", "need": "I need it for my portfolio",
             "forget": ["exact_date_unknown", "event_name_unknown"]},
            {"item": "the photo from the Ganpati procession", "event": "the Ganpati visarjan", "place": "on the road near our society",
             "time": "not sure which year", "visual": "red gulal everywhere and the idol behind us", "person": "my neighbours",
             "kw": "ganpati", "nl": "people covered in red colour with ganesh idol", "meta": "september", "syn": "festival", "need": "our society newsletter wanted old pictures",
             "forget": ["exact_date_unknown"]},
            {"item": "the photo of my daughter on stage at her school play", "event": "the annual day function", "person": "my daughter",
             "time": "when she was in 2nd or 3rd standard", "visual": "a sunflower costume and a blue curtain", "context": "the lighting was bad so most shots were blurry",
             "kw": "school function", "nl": "girl in sunflower costume on stage", "meta": "annual day", "syn": "stage", "need": "she wants to show her friends",
             "forget": ["exact_date_unknown", "event_name_unknown"]},
            {"item": "a shot of the fireworks at the new year party", "event": "the new year party at the club", "person": "a bunch of friends",
             "time": "one of the new years, 2019 or 2020", "visual": "green fireworks over a swimming pool", "context": "it was just before midnight",
             "kw": "fireworks", "nl": "green fireworks over pool", "meta": "31 december", "syn": "new year", "need": "I wanted to post a throwback",
             "forget": ["exact_date_unknown"]},
        ],
    },
    "wedding_memory": {
        "weight": 0.8, "object": "photo",
        "outcomes": {"found": 0.25, "not_found": 0.20, "abandoned": 0.20, "partially_found": 0.20, "uncertain": 0.15},
        "failures": {"D_result_evaluation": 0.45, "F_data_index_limitation": 0.15, "C_retrieval": 0.15, "E_refinement": 0.25},
        "episodes": [
            {"item": "the photo from my friend's wedding where we were standing outside", "event": "my friend's wedding", "place": "outside the venue near the parking area",
             "time": "a couple of years ago, winter", "visual": "me in a maroon sherwani and fairy lights on a gate", "person": "the groom and our school gang",
             "kw": "wedding", "nl": "friends standing outside wedding venue at night", "meta": "wedding december", "syn": "marriage", "need": "it's their anniversary next week",
             "forget": ["exact_date_unknown", "exact_location_unknown"]},
            {"item": "the candid of my cousin laughing during the haldi", "event": "my cousin's haldi", "person": "my cousin",
             "time": "the morning before the wedding, 2023", "visual": "yellow everywhere and marigold flowers", "context": "someone had just thrown haldi on her",
             "kw": "haldi", "nl": "girl laughing covered in yellow with marigolds", "meta": "2023 wedding", "syn": "yellow ceremony", "need": "she wants it for her album",
             "forget": ["exact_date_unknown"]},
            {"item": "the photo with the bride and my grandmother", "event": "my brother's wedding", "person": "my grandmother and my sister-in-law",
             "time": "reception night", "visual": "grandma in a green saree sitting on the stage", "relationship": "one that the photographer's assistant sent us",
             "kw": "grandmother", "nl": "old lady in green saree with bride on stage", "meta": "reception", "syn": "grandma", "need": "grandma wants a print",
             "forget": ["album_unknown", "exact_date_unknown"]},
            {"item": "the photo of us dancing at the sangeet", "event": "the sangeet night", "person": "my husband and his cousins",
             "time": "the night before our wedding", "visual": "a disco ball and me in a pink lehenga", "context": "we had practised that dance for weeks",
             "kw": "dance", "nl": "couple dancing under disco ball pink lehenga", "meta": "sangeet", "syn": "party", "need": "I wanted it for our first anniversary post",
             "forget": ["album_unknown"]},
        ],
    },
    "work_memory": {
        "weight": 0.6, "object": "photo",
        "outcomes": {"found": 0.35, "not_found": 0.30, "abandoned": 0.15, "partially_found": 0.10, "uncertain": 0.10},
        "failures": {"A_memory_expression": 0.3, "F_data_index_limitation": 0.3, "B_system_understanding": 0.2, "E_refinement": 0.2},
        "episodes": [
            {"item": "the photo of the whiteboard from our planning session", "context": "we photographed it after the workshop", "place": "in the small meeting room",
             "time": "sometime last quarter", "visual": "boxes and arrows in red and blue marker", "text": "something about the launch timeline",
             "kw": "whiteboard", "nl": "whiteboard with launch timeline", "meta": "whiteboard march", "syn": "board", "need": "my manager needs the timeline",
             "forget": ["exact_text_unknown", "exact_date_unknown"]},
            {"item": "a picture of the site inspection issue", "place": "at the client's warehouse", "object": "a cracked pipe fitting",
             "time": "a few months back", "visual": "a rusty pipe with a yellow tag", "context": "I took it for the report and never sent it",
             "kw": "pipe", "nl": "rusty pipe with yellow tag at warehouse", "meta": "warehouse", "syn": "plumbing", "need": "the client is disputing the report",
             "forget": ["exact_date_unknown", "exact_object_name_unknown"]},
            {"item": "the photo of the team at the offsite", "event": "the team offsite", "person": "my old team",
             "time": "before I switched jobs, 2021 maybe", "visual": "everyone in matching t-shirts by a pool", "place": "at a resort outside the city",
             "kw": "team", "nl": "team in matching t shirts by a pool", "meta": "offsite 2021", "syn": "office trip", "need": "a colleague is leaving and we're making a card",
             "forget": ["exact_location_unknown", "exact_date_unknown"]},
        ],
    },
    "document": {
        "weight": 1.2, "object": "document_or_receipt",
        "outcomes": {"found": 0.30, "not_found": 0.30, "abandoned": 0.20, "partially_found": 0.10, "uncertain": 0.10},
        "failures": {"F_data_index_limitation": 0.30, "A_memory_expression": 0.25, "C_retrieval": 0.25, "E_refinement": 0.2},
        "episodes": [
            {"item": "the photo I took of my passport page", "object": "my passport", "context": "I took it when applying for a visa",
             "time": "two or three years ago", "text": "the passport number and expiry date", "visual": "my thumb covering one corner",
             "kw": "passport", "nl": "photo of passport page", "meta": "visa 2022", "syn": "id", "need": "I need the number urgently for a booking",
             "forget": ["exact_date_unknown", "exact_text_unknown"]},
            {"item": "a photo of the rental agreement", "object": "the rental agreement", "context": "the landlord only gave us one copy so I photographed every page",
             "time": "when we moved into this flat, 2021 or so", "text": "something about the notice period", "visual": "stamp paper with a purple stamp",
             "kw": "agreement", "nl": "rent agreement document pages", "meta": "agreement 2021", "syn": "contract", "need": "the landlord is refusing to return the deposit",
             "forget": ["exact_text_unknown", "exact_date_unknown"]},
            {"item": "the photo of my car's insurance papers", "object": "the insurance papers", "context": "I took it in the car when the traffic police stopped me once",
             "time": "last year sometime", "text": "the policy number", "visual": "a folded paper on the dashboard",
             "kw": "insurance", "nl": "car insurance paper on dashboard", "meta": "insurance", "syn": "policy", "need": "I had an accident and need the policy number",
             "forget": ["exact_date_unknown", "exact_text_unknown"]},
            {"item": "the photo of my son's vaccination card", "object": "the vaccination card", "context": "the doctor asked us to keep a copy",
             "time": "when he was a baby", "text": "the dates of the last booster", "visual": "a pink card with stamps",
             "kw": "vaccination", "nl": "baby vaccination card pink", "meta": "vaccine", "syn": "immunisation", "need": "school admission needs it",
             "forget": ["exact_text_unknown", "exact_object_name_unknown"]},
            {"item": "the picture of my college marksheet", "object": "my marksheet", "context": "I sent it to some HR at some point",
             "time": "maybe 2020 when I was job hunting", "text": "my semester grades", "visual": "a certificate with a blue border",
             "kw": "marksheet", "nl": "college marksheet with blue border", "meta": "2020 certificate", "syn": "certificate", "need": "background verification asked for it",
             "forget": ["exact_date_unknown", "exact_keyword_unknown"]},
        ],
    },
    "receipt": {
        "weight": 0.9, "object": "document_or_receipt",
        "outcomes": {"found": 0.25, "not_found": 0.35, "abandoned": 0.25, "partially_found": 0.05, "uncertain": 0.10},
        "failures": {"F_data_index_limitation": 0.30, "A_memory_expression": 0.2, "C_retrieval": 0.25, "D_result_evaluation": 0.1, "E_refinement": 0.15},
        "episodes": [
            {"item": "the photo of the bill I took sometime last summer", "object": "a restaurant bill", "context": "we were splitting it between six people",
             "time": "sometime last summer", "text": "the total and the GST number", "visual": "a long crumpled receipt",
             "kw": "bill", "nl": "restaurant bill split between friends", "meta": "june bill", "syn": "receipt", "need": "a friend still hasn't paid me back and disputes the amount",
             "forget": ["exact_date_unknown", "exact_text_unknown"]},
            {"item": "the photo of the warranty card for the washing machine", "object": "the warranty card", "context": "I photographed it right after installation",
             "time": "when we bought it, 2 years ago maybe", "text": "the serial number", "visual": "a small card taped to the invoice",
             "kw": "warranty", "nl": "washing machine warranty card", "meta": "warranty 2024", "syn": "guarantee", "need": "the machine broke and service wants the warranty",
             "forget": ["exact_date_unknown", "exact_text_unknown"]},
            {"item": "the picture of the pharmacy receipt", "object": "a pharmacy bill", "context": "I needed it for insurance reimbursement",
             "time": "around when I was sick last year", "text": "the medicine names and total", "visual": "thermal paper that was already fading",
             "kw": "receipt", "nl": "pharmacy medicine bill", "meta": "pharmacy", "syn": "invoice", "need": "the insurance claim deadline is this week",
             "forget": ["exact_text_unknown", "exact_date_unknown"]},
            {"item": "the photo of the electrician's handwritten estimate", "object": "a handwritten estimate", "context": "he wrote it on a notebook page",
             "time": "a few months ago", "text": "the amount for rewiring", "visual": "blue pen on lined paper",
             "kw": "estimate", "nl": "handwritten estimate on notebook paper", "meta": "electrician", "syn": "quote", "need": "he's charging way more now",
             "forget": ["exact_text_unknown", "exact_date_unknown", "exact_keyword_unknown"]},
        ],
    },
    "medical_or_health_image": {
        "weight": 0.8, "object": "photo",
        "outcomes": {"found": 0.25, "not_found": 0.30, "abandoned": 0.25, "partially_found": 0.10, "uncertain": 0.10},
        "failures": {"A_memory_expression": 0.35, "C_retrieval": 0.2, "F_data_index_limitation": 0.2, "E_refinement": 0.25},
        "episodes": [
            {"item": "the picture of the medicine I took when I was sick last year", "object": "a strip of tablets", "context": "the doctor prescribed it when I had that bad fever",
             "time": "last year, maybe during the rainy season", "visual": "a silver strip with orange tablets", "text": "the medicine name",
             "kw": "medicine", "nl": "medicine strip orange tablets", "meta": "fever medicine", "syn": "tablets", "need": "I'm sick again and want the same medicine",
             "forget": ["exact_object_name_unknown", "exact_text_unknown", "exact_date_unknown"]},
            {"item": "the photo of the rash on my arm", "object": "a rash", "context": "I took it to show the dermatologist how it looked on day one",
             "time": "about eight months ago", "visual": "red patches near my elbow",
             "kw": "rash", "nl": "red rash on arm", "meta": "skin", "syn": "allergy", "need": "the rash is back and the doctor wants to compare",
             "forget": ["exact_date_unknown", "exact_keyword_unknown"]},
            {"item": "the photo of my dad's blood test report", "object": "a lab report", "context": "the lab gave only a paper copy",
             "time": "before his surgery, early last year", "text": "the sugar and cholesterol values", "visual": "a report with a hospital logo",
             "kw": "report", "nl": "blood test report hospital", "meta": "lab report 2025", "syn": "test results", "need": "the new doctor wants old values",
             "forget": ["exact_text_unknown", "exact_date_unknown"]},
            {"item": "the photo of the prescription for my mother's eye drops", "object": "a prescription", "context": "the doctor's handwriting was unreadable",
             "time": "sometime after her cataract surgery", "text": "the name of the eye drops", "visual": "a small slip with a clinic stamp",
             "kw": "prescription", "nl": "doctor prescription eye drops", "meta": "eye clinic", "syn": "doctor note", "need": "the pharmacy needs the name",
             "forget": ["exact_object_name_unknown", "exact_text_unknown"]},
        ],
    },
    "screenshot": {
        "weight": 1.1, "object": "screenshot",
        "outcomes": {"found": 0.30, "not_found": 0.30, "abandoned": 0.20, "partially_found": 0.10, "uncertain": 0.10},
        "failures": {"F_data_index_limitation": 0.25, "A_memory_expression": 0.25, "D_result_evaluation": 0.25, "C_retrieval": 0.25},
        "episodes": [
            {"item": "the screenshot where I had the information about that course", "context": "someone posted it on LinkedIn", "text": "the course fees and the deadline",
             "time": "a few months ago", "visual": "a blue banner with a university logo",
             "kw": "course", "nl": "screenshot of course details with fees", "meta": "screenshot linkedin", "syn": "program", "need": "the application deadline might be close",
             "forget": ["exact_text_unknown", "exact_keyword_unknown", "exact_date_unknown"]},
            {"item": "a screenshot of a recipe from Instagram", "context": "I screenshotted it from a reel", "text": "something with paneer and cashew paste",
             "time": "sometime this year", "visual": "a dark background with white text",
             "kw": "recipe", "nl": "paneer recipe screenshot", "meta": "instagram screenshot", "syn": "cooking", "need": "guests are coming this weekend",
             "forget": ["exact_text_unknown", "exact_keyword_unknown"]},
            {"item": "the screenshot of a chat where my landlord agreed to the repair", "context": "I screenshotted the WhatsApp chat as proof", "text": "him saying he would pay for it",
             "time": "sometime last spring", "person": "my landlord", "visual": "green chat bubbles",
             "kw": "whatsapp", "nl": "screenshot of chat with landlord about repair", "meta": "chat screenshot", "syn": "message", "need": "he's now saying he never agreed",
             "forget": ["exact_text_unknown", "exact_date_unknown"]},
            {"item": "the screenshot of the train booking confirmation", "context": "the email never came so I screenshotted the app", "text": "the PNR number",
             "time": "last month", "visual": "a white screen with a green tick",
             "kw": "ticket", "nl": "train ticket booking confirmation screenshot", "meta": "pnr", "syn": "booking", "need": "the TTE asked for the PNR",
             "forget": ["exact_text_unknown"]},
            {"item": "a screenshot of a map with a pin someone sent", "context": "a friend shared the location of a trekking base camp", "text": "the name of the village",
             "time": "a year or two ago", "visual": "a Google Maps screen with a red pin in the hills",
             "kw": "map", "nl": "map screenshot with pin in mountains", "meta": "maps screenshot", "syn": "location", "need": "I'm finally planning that trek",
             "forget": ["exact_location_unknown", "exact_text_unknown"]},
        ],
    },
    "purchase_related_image": {
        "weight": 0.7, "object": "screenshot",
        "outcomes": {"found": 0.30, "not_found": 0.30, "abandoned": 0.25, "partially_found": 0.10, "uncertain": 0.05},
        "failures": {"A_memory_expression": 0.3, "B_system_understanding": 0.25, "D_result_evaluation": 0.2, "F_data_index_limitation": 0.25},
        "episodes": [
            {"item": "the screenshot of the product I wanted to buy", "context": "I saw it in an ad and screenshotted it", "object": "a lamp",
             "time": "a couple of months ago", "visual": "a brass lamp with a curved neck", "text": "the brand name",
             "kw": "lamp", "nl": "brass lamp with curved neck", "meta": "screenshot lamp", "syn": "light", "need": "there's a sale now",
             "forget": ["exact_object_name_unknown", "exact_text_unknown"]},
            {"item": "the photo of the shoes I tried on in the store", "place": "at a mall", "object": "running shoes",
             "time": "around Diwali sales", "visual": "grey shoes with a neon green sole", "context": "I took it to check the price online later",
             "kw": "shoes", "nl": "grey running shoes with green sole", "meta": "mall october", "syn": "sneakers", "need": "I want to order them online",
             "forget": ["exact_object_name_unknown", "exact_location_unknown"]},
            {"item": "a picture of the sofa fabric sample", "place": "at the furniture shop", "object": "a fabric swatch",
             "time": "when we were redoing the living room", "visual": "a mustard-coloured textured fabric", "context": "the shop said to send them the photo when ordering",
             "kw": "fabric", "nl": "mustard fabric sample", "meta": "furniture shop", "syn": "cloth", "need": "we're finally ordering the sofa",
             "forget": ["exact_object_name_unknown", "exact_date_unknown"]},
        ],
    },
    "location_memory": {
        "weight": 0.6, "object": "photo",
        "outcomes": {"found": 0.35, "not_found": 0.25, "abandoned": 0.15, "partially_found": 0.10, "uncertain": 0.15},
        "failures": {"F_data_index_limitation": 0.35, "C_retrieval": 0.2, "D_result_evaluation": 0.25, "E_refinement": 0.2},
        "episodes": [
            {"item": "that picture from the trip where we stayed near the beach", "place": "at a homestay near a quiet beach", "trip": "a long weekend trip",
             "time": "2021 or 2022, not sure", "visual": "a hammock between two coconut trees", "context": "location was probably off on my phone",
             "kw": "beach", "nl": "hammock between coconut trees near beach homestay", "meta": "beach 2021", "syn": "sea", "need": "I want to book the same homestay",
             "forget": ["exact_location_unknown", "exact_date_unknown", "metadata_unknown"]},
            {"item": "the photo of the parking spot sign", "place": "in a multi-level parking", "context": "I took it so I'd remember where I parked",
             "time": "a few weeks ago", "visual": "a green pillar with a letter and number", "text": "the level and bay number",
             "kw": "parking", "nl": "parking pillar sign", "meta": "parking", "syn": "car park", "need": "I got a parking fine and need to prove where I was",
             "forget": ["exact_text_unknown", "exact_location_unknown"]},
            {"item": "the photo of the temple on the hill", "place": "on a hill somewhere on the way to Mysore", "trip": "a drive with my parents",
             "time": "a long time ago, maybe 2015", "visual": "white steps going up and monkeys on the wall",
             "kw": "temple", "nl": "white temple on hill with steps", "meta": "mysore 2015", "syn": "mandir", "need": "my parents want to visit again",
             "forget": ["exact_location_unknown", "event_name_unknown", "exact_date_unknown"]},
        ],
    },
    "object_memory": {
        "weight": 0.6, "object": "photo",
        "outcomes": {"found": 0.30, "not_found": 0.30, "abandoned": 0.20, "partially_found": 0.10, "uncertain": 0.10},
        "failures": {"A_memory_expression": 0.35, "B_system_understanding": 0.3, "C_retrieval": 0.2, "E_refinement": 0.15},
        "episodes": [
            {"item": "the photo of a plant I saw at a nursery", "place": "at a nursery near my office", "object": "a plant with striped leaves",
             "time": "last spring", "visual": "purple and green striped leaves in a hanging pot",
             "kw": "plant", "nl": "plant with purple striped leaves", "meta": "nursery", "syn": "leaves", "need": "I want to buy it now that I have a balcony",
             "forget": ["exact_object_name_unknown", "exact_location_unknown"]},
            {"item": "a photo of the bookshelf I wanted to build", "object": "a wall shelf", "context": "I saw it at a friend's house",
             "time": "sometime last year", "visual": "wooden shelves shaped like a hexagon", "person": "my friend",
             "kw": "shelf", "nl": "hexagon wooden wall shelf", "meta": "shelf", "syn": "bookcase", "need": "the carpenter is coming tomorrow",
             "forget": ["exact_object_name_unknown", "exact_date_unknown"]},
            {"item": "the picture of the dent on my car", "object": "a dent on the car door", "context": "a scooter hit my car in the parking lot",
             "time": "maybe 6 months ago", "visual": "a scratch on the silver door near the handle",
             "kw": "car", "nl": "dent on silver car door", "meta": "car dent", "syn": "scratch", "need": "the insurance surveyor wants the original photo",
             "forget": ["exact_date_unknown"]},
        ],
    },
    "school_or_college_memory": {
        "weight": 0.5, "object": "photo",
        "outcomes": {"found": 0.30, "not_found": 0.25, "abandoned": 0.25, "partially_found": 0.10, "uncertain": 0.10},
        "failures": {"F_data_index_limitation": 0.3, "D_result_evaluation": 0.2, "E_refinement": 0.3, "C_retrieval": 0.2},
        "episodes": [
            {"item": "the photo from our college fest", "event": "the college cultural fest", "person": "my classmates",
             "time": "second year, so 2014 or 2015", "visual": "all of us in black t-shirts in front of a big banner",
             "kw": "college fest", "nl": "students in black t shirts in front of banner", "meta": "2014", "syn": "fest", "need": "10 year reunion is coming up",
             "forget": ["exact_date_unknown", "event_name_unknown"], "context": "the photos were from an old phone that I backed up later"},
            {"item": "the photo of the notes a friend shared before exams", "object": "handwritten notes", "person": "a classmate",
             "time": "final semester", "text": "something about thermodynamics formulas", "visual": "pages with yellow highlighter",
             "kw": "notes", "nl": "handwritten thermodynamics notes", "meta": "exam notes", "syn": "study notes", "need": "my younger brother needs them now",
             "forget": ["exact_text_unknown", "exact_date_unknown"]},
            {"item": "the class photo from school farewell", "event": "school farewell", "person": "my whole class",
             "time": "2010, I think", "visual": "everyone in sarees and suits on the school steps", "relationship": "a photo of a printed photo my classmate sent",
             "kw": "farewell", "nl": "class photo on school steps sarees suits", "meta": "2010", "syn": "graduation", "need": "our class WhatsApp group is collecting old photos",
             "forget": ["exact_date_unknown", "metadata_unknown"]},
        ],
    },
    "personal_memory": {
        "weight": 0.6, "object": "photo",
        "outcomes": {"found": 0.30, "not_found": 0.25, "abandoned": 0.15, "partially_found": 0.10, "uncertain": 0.20},
        "failures": {"A_memory_expression": 0.3, "B_system_understanding": 0.3, "D_result_evaluation": 0.25, "E_refinement": 0.15},
        "episodes": [
            {"item": "that photo where I was wearing the blue shirt", "visual": "me in a light blue linen shirt against a white wall", "context": "it was the best picture of me in years",
             "time": "maybe two summers ago", "place": "at a friend's place, I think",
             "kw": "blue shirt", "nl": "me wearing blue shirt white wall", "meta": "summer", "syn": "outfit", "need": "I need a profile photo for a new job",
             "forget": ["exact_date_unknown", "exact_location_unknown"]},
            {"item": "the photo of my handwritten letter to myself", "object": "a letter", "context": "I wrote it on my 25th birthday and took a photo before sealing it",
             "time": "my 25th birthday", "text": "some goals for the next five years", "visual": "a cream paper with my messy handwriting",
             "kw": "letter", "nl": "handwritten letter on cream paper", "meta": "birthday", "syn": "note", "need": "I'm turning 30 and wanted to read it",
             "forget": ["exact_text_unknown"]},
            {"item": "the photo of my first tattoo right after I got it", "object": "a tattoo", "context": "it was still covered with cling film",
             "time": "a few years back", "visual": "a small wave design on my wrist, all red around it",
             "kw": "tattoo", "nl": "fresh wave tattoo on wrist", "meta": "tattoo", "syn": "ink", "need": "the artist asked for a before picture",
             "forget": ["exact_date_unknown"]},
        ],
    },
    "video": {
        "weight": 0.7, "object": "video",
        "outcomes": {"found": 0.25, "not_found": 0.30, "abandoned": 0.25, "partially_found": 0.10, "uncertain": 0.10},
        "failures": {"C_retrieval": 0.3, "F_data_index_limitation": 0.3, "D_result_evaluation": 0.2, "A_memory_expression": 0.2},
        "episodes": [
            {"item": "the video of my dog meeting the new puppy", "place": "in our backyard", "person": "our old dog",
             "time": "right after we adopted the puppy, 2020", "visual": "the puppy running circles around him", "emotion": "it's the funniest thing",
             "kw": "dog video", "nl": "video of old dog meeting new puppy", "meta": "2020 video", "syn": "puppy", "need": "our old dog passed away last week",
             "forget": ["exact_date_unknown"]},
            {"item": "a short video of the band at the pub", "place": "at a pub in the old part of town", "event": "a random Friday gig",
             "time": "one weekend, maybe 2022", "visual": "red lights and the singer with a violin", "activity": "singing a cover of some old song",
             "kw": "band", "nl": "video of band with violin red lights pub", "meta": "friday 2022", "syn": "live music", "need": "I want to find the band name",
             "forget": ["event_name_unknown", "exact_location_unknown", "exact_object_name_unknown"]},
            {"item": "the video of my nephew saying his first word", "place": "at my sister's house", "person": "my nephew",
             "time": "when he was around one", "context": "it was a video call I screen-recorded",
             "kw": "baby video", "nl": "baby saying first word video", "meta": "screen recording", "syn": "toddler talking", "need": "it's his first birthday party",
             "forget": ["exact_date_unknown", "metadata_unknown"]},
        ],
    },
}

SEGMENT_PHRASES = {
    "large_library": ["I have over 60,000 photos", "my library is around 35k photos", "I've got about 90k photos and videos",
                      "I have 12 years of photos in there", "there are something like 45,000 pictures in my account"],
    "long_tenure": ["I've used Google Photos since it launched", "been backing up everything since 2015",
                    "I moved all my old phone photos in years ago"],
    "android_device": ["on my Pixel", "on my Samsung", "on Android"],
    "ios_device": ["on my iPhone", "on iOS"],
    "desktop_web": ["on the web version on my laptop", "on photos.google.com from my PC"],
    "frequent_searcher": ["I search in Photos pretty much every day", "I use search a lot for work stuff"],
    "screenshot_heavy": ["I take a ridiculous number of screenshots", "half my library is screenshots"],
    "shared_library": ["my wife and I share a partner library", "a lot of my photos come from shared albums"],
}

NOISE = [
    "Storage is full again and now they want me to pay for more. Too expensive for what it is.",
    "Backup has been stuck on 'preparing' for three days. Very annoying.",
    "Why did they move the sharing button? The new layout is confusing.",
    "The editing tools are great, the magic eraser is really good.",
    "Too many notifications about 'memories' I didn't ask for.",
    "App keeps crashing when I open a large video.",
    "Can't figure out how to download all my photos to a hard drive.",
    "Love the collage feature, made a nice one for my mom.",
    "Face grouping merged my twin daughters into one person lol.",
    "The app is slow to load thumbnails on my old phone.",
    "Shared album invite link doesn't work for my dad.",
    "Please add a dark mode for the web version.",
    "Uploading in original quality eats my data plan.",
    "Deleted photos don't free up space on the phone, confusing.",
    "The locked folder is a nice privacy feature.",
    "I wish the video editor had more music options.",
    "Syncing between my two phones is inconsistent.",
    "Cancelled my subscription, moving everything to an external drive.",
    "Printing service delivery took two weeks.",
    "The widget on the home screen shows the same photo every day.",
]

ADVICE = [
    "Tip: if location history was on, try the map view and zoom into the area instead of searching the name.",
    "Search by year first, like \"2019\", then scroll within that. Much faster than scrolling from today.",
    "Try searching for something visible in the photo instead of what happened, like \"stage\" or \"cake\".",
    "If it was a screenshot, open the Screenshots category first and then scroll by month.",
    "You can search text inside photos sometimes, but it only works if the words are clear in the image.",
    "Check whether the photo was ever backed up. If it was from an old phone it might never have been uploaded.",
    "Name the face groups. Searching a person's name works way better than describing them.",
    "Ask whoever was there, someone in the group chat usually still has it.",
    "Search for the thing plus the city, e.g. \"cake bangalore\", works better than a sentence for me.",
    "Use the date jump on the scrollbar, drag to the year and go month by month.",
]

OPINION = [
    "Search should work the way I remember things, like '{nl}', not just single words.",
    "I don't remember dates, nobody does. Searching by date is useless for old memories.",
    "It's frustrating that I have to guess what word the app uses for something.",
    "I remember photos by who I was with and what we were doing, not by where the GPS says I was.",
    "The search is fine if you know exactly what you want, but not when you only half remember it.",
    "Honestly I've stopped using search and just scroll, it's more predictable.",
    "It would help if the app told me why a photo showed up in results.",
]

SUCCESS = [
    "Honestly search is amazing. I typed \"{nl}\" and it found {item} in seconds.",
    "Was sure I'd never find {item}, but searching \"{kw}\" plus the year got it on the first try.",
    "Didn't remember anything except {visual_any}, searched for that and it showed up. Impressed.",
    "Found {item} by searching the person's face and then scrolling a bit. Took two minutes.",
]

MISATTRIBUTION = [
    "Spent an hour looking for {item} and it turns out I had deleted it years ago. Not the app's fault.",
    "Couldn't find {item} anywhere, then realised it was on my old phone and never got backed up.",
    "Thought search was broken but {item} was in my partner's library, not mine.",
]
